version: '3'

services:
  laravel-app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_KEY=your_app_key_here
      - DB_HOST=mysql
      - DB_DATABASE=your_database
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_username
      - MYSQL_PASSWORD=your_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt # Mount Certbot's data directory
    depends_on:
      - laravel-app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html/public -d safesxpress.com
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
